newspaper/urls.py
from django.urls import path

from .views import (
    index,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorExperienceUpdateView,
    RedactorDeleteView,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    toggle_assign_to_newspaper,
    newspapers_search,
    redactors_search,
    topics_search,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list"
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorExperienceUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "newspapers/search/",
        newspapers_search,
        name="newspapers-search",
    ),
    path(
        "redactors/search/",
        redactors_search,
        name="redactors-search",
    ),
    path(
        "topics/search/",
        topics_search,
        name="topic-search",
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<nav class="navbar navbar-dark bg-dark">
  <div class="container">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{{ user.get_absolute_url }}">
    <i class="material-icons" style="font-size:25px;color:green">verified_user</i>
      {{ user.get_username }}
    </a>
    <a class="navbar-brand" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
  {% else %}
    <a class="navbar-brand" href="{% url 'login'%}?next={{request.path}}">
    <i class="material-icons" style="font-size:25px;color:red">verified_user</i>
      Login
    </a>
  {% endif %}
  </div>
</nav>

<br>

<nav class="navbar navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'newspaper:index' %}">
      <i class="material-icons" style="font-size:25px;color:gray">home</i>
      Home
    </a>
    <a class="navbar-brand" href="{% url 'newspaper:redactor-list' %}">
      <i class="material-icons" style="font-size:25px;color:gray">group</i>
      Redactors
    </a>
    <a class="navbar-brand" href="{% url 'newspaper:newspaper-list' %}">
      <i class="material-icons" style="font-size:25px;color:gray">collections_bookmark</i>
      Newspapers
    </a>
    <a class="navbar-brand" href="{% url 'newspaper:topic-list' %}">
      <i class="material-icons" style="font-size:25px;color:gray">subject</i>
      Topics
    </a>
  </div>
</nav>