newspaper/urls.py
from django.urls import path

from .views import (
    index,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorExperienceUpdateView,
    RedactorDeleteView,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    toggle_assign_to_newspaper,
    newspapers_search,
    redactors_search,
    topics_search,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list"
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorExperienceUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "newspapers/search/",
        newspapers_search,
        name="newspapers-search",
    ),
    path(
        "redactors/search/",
        redactors_search,
        name="redactors-search",
    ),
    path(
        "topics/search/",
        topics_search,
        name="topic-search",
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
import datetime

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("newspaper:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

newspaper/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from newspaper.models import Newspaper, Redactor, Topic


class NewspaperForm(forms.ModelForm):
    topic = forms.ModelChoiceField(
        queryset=Topic.objects.all(),
        initial=0
    )
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = ["title", "content", "topic", "publishers"]


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience_number(self):
        return validate_years_of_experience_number(self.cleaned_data["years_of_experience"])


class RedactorExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["username", "first_name", "last_name", "years_of_experience"]

    def clean_license_number(self):
        return validate_years_of_experience_number(self.cleaned_data["years_of_experience"])


def validate_years_of_experience_number(years_of_experience):
    if years_of_experience < 0 or years_of_experience > 75:
        raise ValidationError("Years of experience are not real!")

    return years_of_experience

newspaper/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import RedactorCreationForm, RedactorExperienceUpdateForm, NewspaperForm
from django.db.models import Q

from newspaper.models import Redactor, Newspaper, Topic


@login_required
def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "newspaper/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "newspaper/topic_list.html"
    paginate_by = 5


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.select_related("topic")


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorExperienceUpdateForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if (
        Newspaper.objects.get(id=pk) in Redactor.newspapers.all()
    ):  # probably could check if Newspaper exists
        redactor.newspapers.remove(pk)
    else:
        redactor.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("newspaper:newspaper-detail", args=[pk]))


def newspapers_search(request):
    search_newspaper = request.GET.get("search")
    if search_newspaper:
        newspaper_list = Newspaper.objects.filter(
            Q(title__icontains=search_newspaper)
            | Q(published_date__contains=search_newspaper)
        )
    else:
        newspaper_list = Newspaper.objects.all().order_by("title")

    context = {
        "newspaper_list": newspaper_list
    }
    return render(request, "newspaper/newspaper_list.html", context=context)


def redactors_search(request):
    redactors_searching = request.GET.get("search")
    if redactors_searching:
        redactor_list = Redactor.objects.filter(
            Q(username__icontains=redactors_searching)
        )
    else:
        redactor_list = Redactor.objects.all().order_by("username")

    context = {
        "redactor_list": redactor_list
    }
    return render(request, "newspaper/redactor_list.html", context=context)


def topics_search(request):
    topics_searching = request.GET.get("search")
    if topics_searching:
        topic_list = Topic.objects.filter(
            Q(name__icontains=topics_searching)
        )
    else:
        topic_list = Topic.objects.all().order_by("name")

    context = {
        "topic_list": topic_list
    }
    return render(request, "newspaper/topic_list.html", context=context)

templates/newspaper/index.html
{% extends "base.html" %}

{% block content %}

  <style>
#div1 {
  font-size:48px;
}
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <h5 class="display-1"><strong>Newspaper agency:</strong>
    <div id="div1" class="fa"></div>
    <i data-mdb-animation-start="onLoad"  class="material-icons" style="font-size:48px;color:gray">border_color</i></h5>
  <br>
  <h5 class="display-2">Newspapers: {{ num_newspapers }}</h5>
  <h5 class="display-3">Redactors: {{ num_redactors }}</h5>
  <h5 class="display-4">Topics: {{ num_topics}}</h5>
  <br>
    <h6>Welcome!</h6>
    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>
  <script>
function openfolder() {
  var a;
  a = document.getElementById("div1");
  a.innerHTML = "&#xf114;";
  setTimeout(function () {
      a.innerHTML = "&#xf115;";
    }, 1000);
}
openfolder();
setInterval(openfolder, 2000);
</script>

{% endblock %}

templates/newspaper/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete newspaper {{ newspaper.title }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  <a href="{% url 'newspaper:newspaper-list' %}"  class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/newspaper/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ newspaper.title }}
    <a href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>Topic: ({{ newspaper.topic.name }})</p>
  <h3>
    Content:
  </h3>
  <ul>
      <li>{{ newspaper.content }} </li>
  </ul>
  <hr>
  <ul>
    {% for redactor in newspaper.redactors.all %}
      <li>{{ redactor.username }} ({{ redactor.first_name }} {{ redactor.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/newspaper/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-secondary">
  </form>
{% endblock %}

templates/newspaper/newspaper_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Newspaper list:
    <a href="{% url 'newspaper:newspaper-create' %}" class="btn btn-secondary link-to-page">
      Create
    </a>
  </h1>
  <form class="form-inline my-2 my-lg-0" action="{% url 'newspaper:newspapers-search' %}">
    <input class="form-control mr-sm-2" type="search" placeholder="Search: title"
           aria-label="Search" name="search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  {% if newspaper_list %}
    <table class="table table-striped">
    <tr>
      <th scope="col">
        ID
      </th>
      <th scope="col">
        Title
      </th>
      <th scope="col">
        Content
      </th>
      <th scope="col">
        Topic
      </th>
      <th scope="col">
        Date
      </th>
      <th scope="col">
        Update
      </th>
      <th scope="col">
        Delete
      </th>
    </tr>
      {% for newspaper in newspaper_list %}
        <tr>
        <td>
          <a href="{% url "newspaper:newspaper-detail" pk=newspaper.id %} ">{{ newspaper.id }}</a>
        </td>
          <td>
            <strong>{{ newspaper.title }}</strong>
          </td>
          <td>
            {{ newspaper.content|slice:"0:350" }}
          </td>
          <td>
            <strong>{{ newspaper.topic.name }}</strong>
          </td>
          <td>
            {{ newspaper.published_date }}
          </td>
          <td>
              <a href="{% url "newspaper:newspaper-update" pk=newspaper.id %}">
                <i class="material-icons" style="font-size:25px;color:gray">update</i>
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url "newspaper:newspaper-delete" pk=newspaper.id %}">
               <i class="material-icons" style="font-size:25px;color:gray">delete</i>
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no newspapers in newspaper agency</p>
  {% endif %}
{% endblock %}

templates/newspaper/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ redactor.username }}?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'newspaper:redactor-list' %}"  class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/newspaper/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ redactor.username }}
  </h1>
  <p><strong>First name:</strong> {{ redactor.first_name }}</p>
  <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
  <p><strong>Experience:</strong> {{ redactor.years_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

  <div class="ml-3">
    <h4>Newspapers:</h4>

    {% for newspaper in redactor.newspapers.all%}
        <hr>
        <p><strong>Title:</strong> {{ newspaper.title }}</p>
        <p><strong>Content:</strong> {{ newspaper.content }}</p>
      <p class="text-muted"><strong>Id:</strong>
        <a href="{% url "newspaper:newspaper-detail" pk=newspaper.id %} "><strong> {{newspaper.id}}</strong></a>
      </p>


    {% empty %}
      <p>No newspapers!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/newspaper/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} redactor:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-secondary">
  </form>
{% endblock %}

templates/newspaper/redactor_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
      Redactor list:
      <a href="{% url 'newspaper:redactor-create' %}" class="btn btn-secondary link-to-page">
        Create
      </a>
    </h1>
  <form class="form-inline my-2 my-lg-0" action="{% url 'newspaper:redactors-search' %}">
    <input class="form-control mr-sm-2" type="search"   placeholder="Search by username"
           aria-label="Search" name="search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>

    {% if redactor_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for redactor in redactor_list %}
      <tr>
        <td>{{ redactor.id }}</td>
        <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
        <td>{{ redactor.first_name }}</td>
        <td>{{ redactor.last_name }}</td>
        <td>{{ redactor.years_of_experience }}</td>
        <td>
              <a href="{% url 'newspaper:redactor-update' pk=redactor.id %}">
                <i class="material-icons" style="font-size:25px;color:gray">update</i>
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'newspaper:redactor-delete' pk=redactor.id %}">
               <i class="material-icons" style="font-size:25px;color:gray">delete</i>
              </a>
            </td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no redactors in the agency.</p>
    {% endif %}
{% endblock %}

templates/newspaper/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic {{ topic.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  <a href="{% url 'newspaper:topic-list' %}"  class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/newspaper/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} topic</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-secondary">
  </form>
{% endblock %}

templates/newspaper/topic_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Topic list:
    <a href="{% url 'newspaper:topic-create' %}" class="btn btn-secondary link-to-page"  >
      Create
    </a>
  </h1>
  <form class="form-inline my-2 my-lg-0" action="{% url 'newspaper:topic-search' %}">
    <input class="form-control mr-sm-2" type="search"
           placeholder="Search: topic name" aria-label="Search" name="search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>

  {% if topic_list %}
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for topic in topic_list %}
        <tr>
          <td>
              {{ topic.id }}
          </td>
          <td>
              {{ topic.name }}
          </td>
          <td>
              <a href="{% url 'newspaper:topic-update' pk=topic.id %}">
                <i class="material-icons" style="font-size:25px;color:gray">update</i>
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'newspaper:topic-delete' pk=topic.id %}">
               <i class="material-icons" style="font-size:25px;color:gray">delete</i>
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no topics in the agency.</p>
  {% endif %}
{% endblock %}